Repository wecode-bootcamp-korea/43-2nd-See-Other-frontend, pull requests merged in 2023-03, with the labels that each got.

#1 [43기 이솜이] Footer Layout 작업
  src/components/Footer/Footer.js
Labels: 멘토 리뷰 요청

#6 [43기 김수미] add : 모달 추가
  public/index.html
  src/components/Modal/Modal.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: 완료

#5 [43기 이솜이] Account layout 작업
  public/images/icoMovie.svg
  public/images/kakao_login_large_wide.png
  public/images/movie1.jpg
  src/components/Footer/Footer.js
  src/pages/Account/Account.js
Labels: Conflict 해결 요청

#3 [43기 김수미] Add : Main Movie Layout
  public/images/@movie_600x855.jpg
  src/components/Common/Common.js
  src/components/Movie/Movie.js
Labels: 완료

#8 [43기 이솜이] Detail modal layout
  public/images/icoMovie.svg
  public/images/movie01.jpg
  src/Router.js
  src/components/Detail/Detail.js
  src/components/Theater/Theater.js
Labels: 멘토 리뷰 요청

#9 [43기 오지수]ADD: Main페이지 SpecialTheater 컴포넌트
  public/images/icoMovie.svg
  public/images/theater.jpg
  src/components/Common/Common.js
  src/components/Header/GroupHead/GroupHead.js
  src/pages/Main/CsCenter/CsCenter.js
  src/pages/Main/Main.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#10 [43기 오지수]ADD: Main 페이지 상단동영상 컴포넌트
  package-lock.json
  package.json
  public/images/icoMovie.svg
  public/images/question.png
  public/images/share.png
  src/assets/VIDEO.js
  src/components/Common/Common.js
  src/components/MainMore/MainMore.js
  src/pages/Main/Main.js
  src/pages/Main/MainSlide/MainSlide.js
  src/pages/Main/SpecialTheater/SpecialTheater.js
Labels: 멘토 리뷰 요청

#18 [43기 오지수] ADD: Main 페이지 변경 및 수정
  src/components/Header/GroupHead/CATE_MENU.js
  src/components/Header/GroupHead/GroupHead.js
  src/components/Movie/Movie.js
  src/pages/Main/Main.js
  src/pages/Main/MainMore/MainMore.js
  src/pages/Main/MainTitle/MainTitle.js
  src/pages/Main/MovieInfo/MovieInfo.js
  src/pages/Main/SpecialTheater/SpecialTheater.js
Labels: 멘토 리뷰 요청

#15 [43기 이솜이] ADD : kakao 소셜 로그인 기능 추가
  .gitignore
  src/Hooks/useFetch.js
  src/Router.js
  src/config.js
  src/pages/Account/Account.js
  src/pages/Account/component/AccountData.js
  src/pages/Account/component/Kakao.js
Labels: 멘토 리뷰 요청

#16 [43기 오지수] ADD: 티켓예매 페이지 하단바 UI (Feature/ticket footer)
  public/images/pooh.png
  src/pages/QuickMenu/QuickMenu.js
  src/pages/Ticket/Ticket.js
Labels: 멘토 리뷰 요청

#19 [43기 김수미] 무비차트 디테일 평점 리뷰 기능 추가
  src/components/Detail/Detail.js
  src/components/Detail/FormReview/FormReview.js
  src/components/Detail/ListReview/ListReview.js
  src/components/Detail/Movie/Movie.js
  src/components/Detail/Review/Review.js
Labels: 멘토 리뷰 요청
